#!/bin/bash
# warp-mesh 初始化脚本 — 在 docker compose up 之前运行
# 根据角色生成 gost.yaml（如果不存在）
#
# 用法: ./init.sh [node|relay|client] [GOST_REMOTE]
# 示例: ./init.sh relay socks5://100.96.0.42:1080
#       ./init.sh node
#       ./init.sh client socks5://001:pass@100.96.0.42:1080

set -e

ROLE="${1:-node}"
GOST_REMOTE="${2:-}"
GOST_FILE="./gost/gost.yaml"
mkdir -p "$(dirname "${GOST_FILE}")"

if [ -f "${GOST_FILE}" ]; then
  echo "[INFO] ${GOST_FILE} already exists, skipping generation"
  echo "[INFO] To regenerate, delete it first: rm ${GOST_FILE}"
  exit 0
fi

BIND="${GOST_BIND:-0.0.0.0}"
SOCKS_PORT="${GOST_SOCKS_PORT:-1080}"
HTTP_PORT="${GOST_HTTP_PORT:-8080}"
REDIRECT_PORT="${GOST_REDIRECT_PORT:-12345}"

# 解析 GOST_REMOTE
REMOTE_ADDR=""
REMOTE_PROTO="socks5"
REMOTE_USER=""
REMOTE_PASS=""
if [ -n "${GOST_REMOTE}" ]; then
  case "${GOST_REMOTE}" in
    *://*) REMOTE_PROTO="${GOST_REMOTE%%://*}"; REMOTE_ADDR="${GOST_REMOTE#*://}" ;;
    *) REMOTE_ADDR="${GOST_REMOTE}" ;;
  esac
  case "${REMOTE_ADDR}" in
    *@*)
      USERINFO="${REMOTE_ADDR%%@*}"
      REMOTE_USER="${USERINFO%%:*}"
      REMOTE_PASS="${USERINFO#*:}"
      REMOTE_ADDR="${REMOTE_ADDR#*@}"
      ;;
  esac
  [ "${REMOTE_PROTO}" = "socks5h" ] && REMOTE_PROTO="socks5"
fi

# 本地认证
LOCAL_AUTH=""
if [ -n "${GOST_USER}" ] && [ -n "${GOST_PASS}" ]; then
  LOCAL_AUTH="yes"
fi

cat > "${GOST_FILE}" << EOF
# GOST config for ${ROLE} role — auto-generated by init.sh
# Edit this file directly, then: docker compose restart

services:
  - name: socks5-service
    addr: "${BIND}:${SOCKS_PORT}"
    handler:
      type: socks5
EOF

if [ -n "${LOCAL_AUTH}" ]; then
  cat >> "${GOST_FILE}" << EOF
      auth:
        username: "${GOST_USER}"
        password: "${GOST_PASS}"
EOF
fi

if [ -n "${REMOTE_ADDR}" ]; then
  echo "      chain: gost-chain" >> "${GOST_FILE}"
fi

cat >> "${GOST_FILE}" << EOF
    listener:
      type: tcp

  - name: http-service
    addr: "${BIND}:${HTTP_PORT}"
    handler:
      type: http
EOF

if [ -n "${LOCAL_AUTH}" ]; then
  cat >> "${GOST_FILE}" << EOF
      auth:
        username: "${GOST_USER}"
        password: "${GOST_PASS}"
EOF
fi

if [ -n "${REMOTE_ADDR}" ]; then
  echo "      chain: gost-chain" >> "${GOST_FILE}"
fi

cat >> "${GOST_FILE}" << EOF
    listener:
      type: tcp
EOF

# Client 角色：加透明代理 redirect handler
if [ "${ROLE}" = "client" ]; then
  cat >> "${GOST_FILE}" << REDEOF

  - name: redirect-service
    addr: ":${REDIRECT_PORT}"
    handler:
      type: red
      chain: gost-chain
      metadata:
        sniffing: true
    listener:
      type: red
REDEOF
fi

  - name: redirect-service
    addr: ":${REDIRECT_PORT}"
    handler:
      type: auto
EOF
  if [ -n "${REMOTE_ADDR}" ]; then
    echo "      chain: gost-chain" >> "${GOST_FILE}"
  fi
  cat >> "${GOST_FILE}" << EOF
    listener:
      type: tcp
EOF
fi

if [ -n "${REMOTE_ADDR}" ]; then
  cat >> "${GOST_FILE}" << EOF

chains:
  - name: gost-chain
    hops:
      - name: hop-remote
        nodes:
          - name: remote-node
            addr: ${REMOTE_ADDR}
            connector:
              type: ${REMOTE_PROTO}
EOF
  if [ -n "${REMOTE_USER}" ]; then
    cat >> "${GOST_FILE}" << EOF
              auth:
                username: "${REMOTE_USER}"
                password: "${REMOTE_PASS}"
EOF
  fi
  cat >> "${GOST_FILE}" << EOF
            dialer:
              type: tcp
EOF
fi

cat >> "${GOST_FILE}" << EOF

log:
  level: info
  format: text
  output: stdout
EOF

echo "[OK] Generated ${GOST_FILE} for role: ${ROLE}"
[ -n "${GOST_REMOTE}" ] && echo "     Remote: ${GOST_REMOTE}"
[ "${ROLE}" = "client" ] && echo "     Transparent proxy: redirect :${REDIRECT_PORT} (iptables)"
echo ""
echo "Next: docker compose up -d"
